//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_classroom : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean rightTrigger
        {
            get
            {
                return SteamVR_Actions.classroom_rightTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean leftTrigger
        {
            get
            {
                return SteamVR_Actions.classroom_leftTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean rightSpawnDesk
        {
            get
            {
                return SteamVR_Actions.classroom_rightSpawnDesk;
            }
        }
        
        public virtual SteamVR_Action_Boolean rightSpawnChair
        {
            get
            {
                return SteamVR_Actions.classroom_rightSpawnChair;
            }
        }
        
        public virtual SteamVR_Action_Boolean leftGrip
        {
            get
            {
                return SteamVR_Actions.classroom_leftGrip;
            }
        }
        
        public virtual SteamVR_Action_Boolean rightGrip
        {
            get
            {
                return SteamVR_Actions.classroom_rightGrip;
            }
        }
        
        public virtual SteamVR_Action_Boolean switchControls
        {
            get
            {
                return SteamVR_Actions.classroom_switchControls;
            }
        }
        
        public virtual SteamVR_Action_Boolean leftSpawnDesk
        {
            get
            {
                return SteamVR_Actions.classroom_leftSpawnDesk;
            }
        }
        
        public virtual SteamVR_Action_Boolean leftSpawnChair
        {
            get
            {
                return SteamVR_Actions.classroom_leftSpawnChair;
            }
        }
    }
}
